name: mindwaves
description: Fully open-source mood tracker with AI integration and real-time notifications to keep track of your life.
version: 1.0.0

publish_to: 'none'


environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1

  graphic: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/