name: mindwaves
description: Fully open-source mood tracker with AI integration and real-time notifications to keep track of your life.
version: 1.0.0

publish_to: 'none'


environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  http: ^1.1.0

  # Time related packages
  intl: ^0.18.1 # formatting
  timezone: ^0.9.2 # timezones

  # Notifications!
  flutter_local_notifications: ^16.1.0

  # Graphs
  graphic: ^2.2.0

  # Animations
  lottie: ^2.6.0

  # Encryption with AES
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/